name: SCALE Tests
on:
  repository_dispatch:
    types: [run-scale-tests-command]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Configure
      run: |
        mkdir -p tests/singlerod/short/build
        cd tests/singlerod/short/build
        CC=mpicc CXX=mpicxx FC=mpifort cmake -DUSR_LOC=.. -DSCALE_DIR=/opt/scale/6.3-dev ../../../..

    - name: Build
      run: |
        cd tests/singlerod/short/build
        make -j
