name: SCALE Tests
on:
  repository_dispatch:
    types: [run-scale-tests-command]

jobs:
  build:
    runs-on: self-runner

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Configure
      run: |
        echo $(pwd)
